app:
    resource: "@AppBundle/Controller/"
    type:     annotation

accueil:
    path:      /
    defaults:  { _controller: AppBundle:Perturbation:index }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"