app:
    resource: "@AppBundle/Controller/"
    type:     annotation
accueil:
    path:      /
    defaults:  { _controller: AppBundle:Perturbation:listNearest }
#app_routing:
#    resource: "@AppBundle/Resources/config/routing.yml"
#    type:     yml
login:
    path: /login 
    defaults:  { _controller: AppBundle:User:login }
accueil:
    path: /