transport:
    resource: "@TransportBundle/Controller/"
    type:     annotation
    prefix:   /

network:
    resource: "@NetworkBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

accueil:
    path:      /
    defaults:  { _controller: AppBundle:Perturbation:index }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"