# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Particulier:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_PROFESSIONNAL:   ROLE_USER
        ROLE_ADMIN:           ROLE_PROFESSIONNAL

    providers:
        main_provider:
            entity:
                class: AppBundle\Entity\Particulier
                property: username

    firewalls:
        dev_firewall:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/login$
            security: false

        main_firewall:
            pattern: ^/
            anonymous: ~
            provider: main_provider
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/perturbation/list/nearest, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
