# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Particulier:
            algorithm: bcrypt

    providers:
         our_db_provider:
            entity:
                class: AppBundle:Particulier

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        accueil:
            pattern: ^/$
            anonymous: true 
            provider: our_db_provider

        register:
            pattern:  ^/(register|login|js)$
            anonymous: true 
            http_basic: ~
            provider: our_db_provider

        main:
            pattern: ^/
            anonymous: false
            http_basic: ~
            provider: our_db_provider
