# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\Particulier:
            algorithm: bcrypt

    providers:
         our_db_provider:
            entity:
                class: AppBundle:Particulier

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        accueil:
            pattern: ^/$
            anonymous: true 
            provider: our_db_provider

        register:
            pattern:  ^/(register|login|js)$
            anonymous: true 
            http_basic: ~
            provider: our_db_provider

       # logout: true 
        #logout:
            #path : logout

        main:   
            pattern:   ^/
            anonymous: true
            http_basic: ~
            provider: our_db_provider

       #main:
            #pattern:    ^/
            #http_basic: ~
            #provider: our_db_provider

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
           pattern: ^/(_(profiler|wdt)|css|images|js)/
           security: false

        #main:
          #  anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
