<?php

namespace AppBundle\Repository;

/**
 * FormulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulationRepository extends \Doctrine\ORM\EntityRepository
{
}
