<?php

namespace AppBundle\Repository;

/**
 * ObjetTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetTerrainRepository extends \Doctrine\ORM\EntityRepository
{
}
