<?php

namespace AppBundle\Repository;

//use \Doctrine\ORM\Query; // Query::HYDRATE_ARRAY
use AppBundle\Entity\ObjetTerrain;
/**
 * ObjetTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetTerrainRepository extends \Doctrine\ORM\EntityRepository
{

	public function findNearest($position, $rayon) {

		$objets = $this->createQueryBuilder('o')
			->select('o')
			->join('AppBundle:TypeObjetTerrain', 't', 'WITH', 'o.type = t.id')
			->where('ST_DISTANCE(o.position, '.$position.') < :rayon')
			->setParameter('rayon', $rayon)
			->andWhere('t.radius > :radius')
			->setParameter('radius', round($rayon))
			->setMaxResults(350)
			->getQuery()
			->getResult();

		return $objets;

	}

}
