<?php

namespace AppBundle\Repository;

/**
 * ObjetTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetTerrainRepository extends \Doctrine\ORM\EntityRepository
{

	public function findNearest($position, $rayon) {

		$qb = $this->createQueryBuilder('a');

		$objets = $qb->where('ST_DISTANCE(a.position, '.$position.') < :rayon')
			->setParameter('rayon', $rayon)
			//->orderBy('a.creation_date', 'DESC')
			->setMaxResults(350)
			->getQuery()
			->getResult();

		return $objets;

	}

}
