<?php

namespace AppBundle\Repository;

/**
 * particulierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class particulierRepository extends \Doctrine\ORM\EntityRepository
{
}
