<?php

namespace AppBundle\Repository;

/**
 * PerturbationFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerturbationFileRepository extends \Doctrine\ORM\EntityRepository
{
}
