<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\Query;
use \Doctrine\ORM\Query\Expr\Join;
use \Doctrine\ORM\EntityRepository;

/**
 * PerturbationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerturbationRepository extends EntityRepository
{

	public function findNearest($position, $rayon) {

		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
			->innerJoin('p.formulations', 'f')
			->innerJoin('f.type', 't')
			->where('ST_DISTANCE(f.center, '.$position.') < :rayon')
			->setParameter('rayon', $rayon)
			->groupBy('p.id')
		;

		$result = $qb->getQuery()->getResult();

		return $result;

	}
}
