<?php

namespace AppBundle\Repository;

/**
 * PerturbationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerturbationRepository extends \Doctrine\ORM\EntityRepository
{
}
