<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\Query;
use \Doctrine\ORM\Query\Expr\Join;
use \Doctrine\ORM\EntityRepository;

/**
 * PerturbationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerturbationRepository extends EntityRepository
{

	public function findNearest($position, $rayon) {

		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
			->innerJoin('p.formulations', 'f')
			->innerJoin('f.type', 't')
			->where('ST_DISTANCE(f.center, '.$position.') < :rayon')
			->andWhere('p.activated = true')
			->andWhere('p.terminated = false')
			->andWhere('p.archived = false')
			->setParameter('rayon', $rayon)
			->groupBy('p.id')
			->orderBy('p.id', 'DESC')
		;

		$result = $qb->getQuery()->getResult();

		return $result;

	}

	public function findOld() {

		$qb = $this->createQueryBuilder('p');

		$qb->select('p')
			->innerJoin('p.formulations', 'f')
			->where('f.endDate < :now')
			->setParameter('now', new \DateTime())
			->andWhere('p.terminated = false')
			->andWhere('p.archived = false')
			->orderBy('p.id', 'DESC')
			->groupBy('p.id')
		;

		$result = $qb->getQuery()->getResult();

		return $result;

	}

}
