<?php

namespace AppBundle\Repository;

/**
 * TypeObjetTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\EntityRepository;

class TypeObjetTerrainRepository extends \Doctrine\ORM\EntityRepository
{
}
