<?php

namespace AppBundle\Repository;

/**
 * TypePerturbationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePerturbationRepository extends \Doctrine\ORM\EntityRepository
{
}
