<?php

namespace AppBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
}
/*TEMP :

	public function findOneByGroupe($id_groupe, $rang)
	{
		$choix = $this->createQueryBuilder('c')
			->where('c.groupeChoix = :id_groupe')
			->setParameter('id_groupe', $id_groupe)
			->andWhere('c.rang = :rang')
			->setParameter('rang', $rang)
			->getQuery()
			->getResult();
		if ($choix != null){
			return $choix[0];
		}
		return null;
	}*/