<?php

namespace TransportBundle\Repository;

/**
 * AccessRestrictionValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRestrictionValueRepository extends \Doctrine\ORM\EntityRepository
{
}
