<?php

namespace TransportBundle\Repository;

/**
 * AccessRestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRestrictionRepository extends \Doctrine\ORM\EntityRepository
{
}
