<?php

namespace TransportBundle\Repository;

/**
 * FormOfRoadNodeValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormOfRoadNodeValueRepository extends \Doctrine\ORM\EntityRepository
{
}
