<?php

namespace TransportBundle\Repository;

/**
 * RestrictionForVehiclesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionForVehiclesRepository extends \Doctrine\ORM\EntityRepository
{
}
