<?php

namespace TransportBundle\Repository;

/**
 * RestrictionTypeValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionTypeValueRepository extends \Doctrine\ORM\EntityRepository
{
}
