<?php

namespace TransportBundle\Repository;

use \Doctrine\ORM\Query;
use \Doctrine\ORM\EntityRepository;

/**
 * RoadLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoadLinkRepository extends \Doctrine\ORM\EntityRepository
{
	public function findNearest($position, $rayon) {

		$qb = $this->createQueryBuilder('l');

		$qb->select('l')
			->where('ST_DISTANCE(ST_GeomFromText(l.centrelineGeometry, 4326), '.$position.') < :rayon')
			->setParameter('rayon', $rayon)
			->orderBy('l.inspireId', 'DESC')
		;

		$result = $qb->getQuery()->getResult();

		return $result;

	}
}
