<?php

namespace TransportBundle\Repository;

use \Doctrine\ORM\Query;
use \Doctrine\ORM\EntityRepository;

/**
 * RoadNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoadNodeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findNearest($position, $rayon) {

		$qb = $this->createQueryBuilder('n');

		$qb->select('n')
			->where('ST_DISTANCE(ST_GeomFromText(n.geometry, 4326), '.$position.') < :rayon')
			->setParameter('rayon', $rayon)
			->orderBy('n.inspireId', 'DESC')
		;

		$result = $qb->getQuery()->getResult();

		return $result;

	}
}
