<?php

namespace TransportBundle\Repository;

/**
 * RoadLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoadLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
