<?php

namespace TransportBundle\Repository;

/**
 * RoadNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoadNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
