<?php

namespace TransportBundle\Repository;

/**
 * TrasportNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrasportNodeRepository extends \Doctrine\ORM\EntityRepository
{
}
