<?php

namespace TransportBundle\Repository;

/**
 * WeatherConditionValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherConditionValueRepository extends \Doctrine\ORM\EntityRepository
{
}
