<?php

namespace TransportBundle\Repository;

/**
 * WeatherConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeatherConditionRepository extends \Doctrine\ORM\EntityRepository
{
}
