<?php

namespace NetworkBundle\Repository;

/**
 * GeneralisedLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralisedLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
